### ISSUE TITLE
api接口挂了貌似。

### ISSUE THREAD

**Issue by DengYuncheng27** [Nthily/KFC-Crazy-Thursday#107]
api接口挂了貌似。。。
![image](https://user-images.githubusercontent.com/56923863/191645490-28fda8b8-70f7-4c87-b181-a3e0946ba464.png)

**Comment by Nthily** [comment]
不能直连了

**Comment by DengYuncheng27** [comment]
## 那我该怎么请求呢？
看留下的就一个链接，不知道该怎么请求，需要什么参数吗？还是需要特定的请求方式呀。

**Comment by Nthily** [comment]
Get 请求拿到 response body 就可以了

**Comment by DengYuncheng27** [comment]
> Get 请求拿到 response body 就可以了

对呀，，浏览器默认不是get请求来着吗。。。

然后发现现在恢复了，， 感谢。🙇‍


![image](https://user-images.githubusercontent.com/56923863/191649117-3c207c02-32dc-425a-9d31-5911ebc828b3.png)

**Comment by DengYuncheng27** [comment]
## 已解决，需要挂梯子访问。
不挂梯子访问不了，挂梯子后成功访问，感谢。 
这个issue就关啦。
