### ISSUE TITLE
App 联动请求

### ISSUE THREAD

**Issue by shensven** [Nthily/KFC-Crazy-Thursday#64]
仓库作者你好，我是 Sven，最近撸了一个 App，用到了你仓库里的文案，想询问你是否可以，以某种许可证或者知识共享的方式，授权给我的 App 使用，我可以为你署名。

App 源码仓库如下
https://github.com/shensven/Crazy-Thursday

**Comment by Nthily** [comment]
没问题可以随便用

**Comment by shensven** [comment]
非常感谢 @Nthily
