### ISSUE TITLE
朋友找我借钱

### ISSUE THREAD

**Issue by zjw-swun** [Nthily/KFC-Crazy-Thursday#9]
我想问一下，之前朋友找我借钱，前后加起来有大概七万（够立案）但是没有借条也没有字据，微信也早已互删没有任何关于借的字眼，只有支付宝上还有转账记录，派出所刚让我把转账记录发给他看一下的时候，我点支付宝点歪了，不小心点开了肯德基，发现今天是疯狂星期四，谁请我吃？

**Comment by Nthily** [comment]
这个有了
